# Fichier de configuration du docker compose pour prendre en compte le script d'initialisation au lancement du docker compose.
# Dans le repertoire courant, créer un dossier init.sql qui contiendra le script "init.sql" qui initilialisera la base afin
# afin de permettre à l'extracteur d'y recopier les données.
version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ref
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d
